// <auto-generated />
using System;
using GitWorld.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GitWorld.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251231075021_AddEloField")]
    partial class AddEloField
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GitWorld.Shared.Entities.Battle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<Guid>("Player1Id")
                        .HasColumnType("uuid")
                        .HasColumnName("player1_id");

                    b.Property<Guid>("Player2Id")
                        .HasColumnType("uuid")
                        .HasColumnName("player2_id");

                    b.Property<Guid?>("WinnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("winner_id");

                    b.HasKey("Id");

                    b.HasIndex("Player1Id");

                    b.HasIndex("Player2Id");

                    b.HasIndex("WinnerId");

                    b.ToTable("battles", (string)null);
                });

            modelBuilder.Entity("GitWorld.Shared.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Armadura")
                        .HasColumnType("integer")
                        .HasColumnName("armadura");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("Critico")
                        .HasColumnType("integer")
                        .HasColumnName("critico");

                    b.Property<int>("Dano")
                        .HasColumnType("integer")
                        .HasColumnName("dano");

                    b.Property<int>("Derrotas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("derrotas");

                    b.Property<int>("Elo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1000)
                        .HasColumnName("elo");

                    b.Property<int>("Evasao")
                        .HasColumnType("integer")
                        .HasColumnName("evasao");

                    b.Property<long>("GitHubId")
                        .HasColumnType("bigint")
                        .HasColumnName("github_id");

                    b.Property<string>("GitHubLogin")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("github_login");

                    b.Property<int>("Hp")
                        .HasColumnType("integer")
                        .HasColumnName("hp");

                    b.Property<int>("HpMax")
                        .HasColumnType("integer")
                        .HasColumnName("hp_max");

                    b.Property<DateTime>("LastGitHubSync")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_github_sync");

                    b.Property<string>("Reino")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("reino");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("VelocidadeAtaque")
                        .HasColumnType("integer")
                        .HasColumnName("velocidade_ataque");

                    b.Property<int>("VelocidadeMovimento")
                        .HasColumnType("integer")
                        .HasColumnName("velocidade_movimento");

                    b.Property<int>("Vitorias")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("vitorias");

                    b.Property<float>("X")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(5000f)
                        .HasColumnName("x");

                    b.Property<float>("Y")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(5000f)
                        .HasColumnName("y");

                    b.HasKey("Id");

                    b.HasIndex("GitHubId")
                        .IsUnique();

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("GitWorld.Shared.Entities.Battle", b =>
                {
                    b.HasOne("GitWorld.Shared.Entities.Player", "Player1")
                        .WithMany("BattlesAsPlayer1")
                        .HasForeignKey("Player1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GitWorld.Shared.Entities.Player", "Player2")
                        .WithMany("BattlesAsPlayer2")
                        .HasForeignKey("Player2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GitWorld.Shared.Entities.Player", "Winner")
                        .WithMany("BattlesWon")
                        .HasForeignKey("WinnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Player1");

                    b.Navigation("Player2");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("GitWorld.Shared.Entities.Player", b =>
                {
                    b.Navigation("BattlesAsPlayer1");

                    b.Navigation("BattlesAsPlayer2");

                    b.Navigation("BattlesWon");
                });
#pragma warning restore 612, 618
        }
    }
}
